import { NextHubConfig } from '../models/NextHubConfig';

export const PorndigConfig: NextHubConfig = {
    enable: true,
    displayname: "Porndig",
    host: "https://www.porndig.com",
    menu: {
        route: {
            cat: "{host}/channels/{cat}/page/{page}"
        },
        categories: {
            "4K": "1172/uhd-4k",
            "Анал": "33/anal",
            "Анал Вирджины": "89/anal-virgins",
            "Арабки": "91/arab",
            "Азиатки": "38/asian",
            "BBW": "46/bbw",
            "БДСМ": "55/bondage-bdsm",
            "Пляжное порно": "1240/beach-porn",
            "Большие попы": "1198/big-ass",
            "Большие сиськи": "43/big-boobs",
            "Большие члены": "802/big-dick",
            "Черные": "45/black",
            "Черные попы": "878/black-booty",
            "Блондинки": "36/blonde",
            "Минет": "52/blowjob",
            "Бокеп": "1241/bokep",
            "Брюнетки": "63/brunette",
            "Буккаке": "59/bukkake",
            "CFNM": "1226/cfnm",
            "Кастинг": "87/casting-porno",
            "Компиляция": "1127/compilation",
            "Косплей": "1233/cosplay",
            "Кримпай": "47/creampie",
            "Куколд": "1236/cuckold",
            "Глотание спермы": "35/cum-swallowing",
            "Сперма": "799/cumshot",
            "Кунилингус": "1173/cunnilingus",
            "Глубокий минет": "80/deep-throat",
            "Доминирование": "73/domination",
            "Двойное проникновение": "64/double-penetration",
            "Эмо Готика": "83/emo-gothic",
            "Европейское": "1117/european",
            "Бывшая девушка": "820/ex-girlfriend",
            "Эксгибиционизм": "803/exhibitionist",
            "Экстрим": "807/extreme",
            "Факал": "50/facial-ejaculation",
            "Женское": "65/female-friendly",
            "Фемдом": "1225/femdom",
            "Фетиш": "57/fetish",
            "Фистинг": "66/fist-fucking",
            "Фут фетиш": "875/foot-fetish",
            "Full HD": "882/full-hd",
            "Гангбанг": "82/gangbang",
            "Глорихол": "1199/gloryhole",
            "Золотой дождь": "85/golden-shower",
            "Бабушки": "814/grandma",
            "Волосатая пизда": "855/hairy-pussy",
            "Хардкор": "1235/hardcore",
            "Хентай": "51/hentai",
            "Хентай 3D": "1230/hentai-3d",
            "Хентай без цензуры": "1231/hentai-uncensored",
            "Межрасовое": "53/interracial",
            "Латинки": "54/latina",
            "Лесби": "40/lesbian",
            "МИЛФ": "39/milf",
            "Массаж": "74/massage",
            "Мастурбация": "48/masturbation",
            "Зрелые": "41/mature",
            "Зрелые и молодые": "77/mature-and-young-guy",
            "Карлики": "87/midgets",
            "Натуральные большие сиськи": "93/natural-big-tits",
            "Медсестра": "1234/nurse",
            "Масло": "1175/oil",
            "Старик и подростки": "76/old-man-young-girl",
            "Оргия": "42/orgy",
            "На природе": "884/outdoor",
            "POV": "58/pov",
            "Порнозвезды": "879/pornstar",
            "Беременные": "860/pregnant",
            "Рыжие": "60/redhead",
            "Римминг": "1125/rimming",
            "Секретарша": "115/secretary",
            "Секс игрушки": "856/sextoys",
            "Сексуальное белье": "75/sexy-lingerie",
            "Маленькие сиськи": "67/small-tits",
            "Курение": "822/smoking",
            "Мягкое": "805/soft",
            "Соло": "178/solo",
            "Подглядывание": "810/spying",
            "Сквирт": "68/squirters",
            "Сводная семья": "1197/step-family",
            "Чулки": "816/stockings",
            "Страпон": "819/strapon",
            "Студентки": "79/student",
            "Трое": "1043/threesome",
            "Титфак": "86/tit-wank",
            "Униформа": "84/uniforms",
            "Апскирт": "1227/upskirt",
            "Винтаж": "850/vintage",
            "Жесткий секс": "1042/violent-sex",
            "Девственницы": "88/virgin",
            "Вебкамера": "70/webcam",
            "XXX Сценарии": "90/xxx-scenario",
            "Молодые": "34/young",
            "Молодые черные": "812/young-black"
        }
    },
    list: { uri: "video/page/{page}" },
    search: { uri: "channels/33/{search}/page/{page}" },
    contentParse: {
        nodes: "//section[contains(@class, 'video_item_wrapper even_item video_item_medium')]",
        name: { node: ".//a" },
        href: { node: ".//a", attribute: "href" },
        img: { node: ".//img[@class='thumb_preview hidden']", attribute: "data-src" },
        duration: { node: ".//div[@class='bubble bubble_duration']//span" },
        preview: { node: ".//img[contains(@class, 'js_video_preview')]", attribute: "data-vid" }
    },
    view: {
        related: true,
        iframe: {
            pattern: "<link rel=\"prefetch\" as=\"document\" href=\"([^\"]+)\""
        },
        regexMatch: {
            matches: ["/master.mpd", "_2160.mp4", "_1080.mp4", "_720.mp4", "_540.mp4", "_468.mp4", "_360.mp4"],
            pattern: "\"src\":\"([^\"]+{value})\""
        }
    }
}; 